# Example Project Configuration
project: example
name: サンプルプロジェクト
description: |
  LLM協調組織の動作確認用サンプルプロジェクト。
  各LLMに役割を割り当て、簡単なタスクを実行する。

# 役割とLLMの割り当て
role_assignments:
  pm: gemini           # Gemini が PM を担当
  architect: claude    # Claude がアーキテクトを担当
  implementer: opencode  # OpenCode が実装を担当
  implementer_assistant: lfm  # LFM（ローカル）が実装補助を担当
  reviewer: claude     # Claude がレビューを担当
  qa: gemini           # Gemini が QA を担当

# ワークフロー定義
workflow:
  - step: 1
    role: pm
    action: 要件分析
    description: ユーザーの要件を分析し、タスクに分解する

  - step: 2
    role: architect
    action: 設計
    description: PMからの要件を受けて、システム設計を行う

  - step: 3
    role: implementer
    action: 実装
    description: アーキテクトの設計に従ってコードを実装する

  - step: 4
    role: reviewer
    action: コードレビュー
    description: 実装されたコードをレビューする

  - step: 5
    role: implementer
    action: レビュー指摘修正
    description: レビュー指摘を反映する
    condition: レビューで要修正の場合

  - step: 6
    role: qa
    action: 結合テスト・E2Eテスト
    description: 結合テストとE2Eテストを設計・実行する

  - step: 7
    role: implementer
    action: バグ修正
    description: QAで発見されたバグを修正する
    condition: バグが発見された場合

  - step: 8
    role: qa
    action: リリース判定
    description: 受入基準に基づいた最終確認とリリース判定
    output: GO/NO-GO判定

# 評価基準（品質比較用）
evaluation:
  metrics:
    - name: 完了率
      description: タスクの完了率
    - name: コード品質
      description: レビュー指摘の数と深刻度
    - name: バグ発見数
      description: QAで発見されたバグの数
    - name: 設計の一貫性
      description: 設計仕様と実装の整合性
    - name: 実行時間
      description: 各ステップにかかった時間
    - name: リリース成功率
      description: QA判定がGOになった率
